# Generated by Django 3.2 on 2022-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221112_1914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professor',
        ),
        migrations.RemoveField(
            model_name='personinevent',
            name='events',
        ),
        migrations.RemoveField(
            model_name='personinevent',
            name='persons',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='persons',
        ),
        migrations.AddField(
            model_name='event',
            name='modality',
            field=models.CharField(choices=[('VIRTUAL', 'Virtual'), ('PRESENCIAL', 'Presencial')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('CHARLA', 'Charla'), ('EVENTO', 'Evento'), ('CONFERENCIA', 'Conferencia'), ('CICLO', 'Ciclo')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='theme',
            field=models.CharField(choices=[('SALUD', 'Salud'), ('HABITOS', 'Hábitos'), ('EXTRAS', 'Extras'), ('UNION', 'Unión')], default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='PersonInEvent',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
