# Generated by Django 4.1.1 on 2022-09-18 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("drugbank", "0001_initial"),
        ("institution", "0001_initial"),
        ("person", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthprofessional",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                parent_link=True,
                to="person.person",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="care_taker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="persons",
                to="person.person",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="health_insurance",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="person.healthinsurance",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="medication",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="drugbank.drug",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                parent_link=True,
                to="person.person",
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="address",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="created_at",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="dni",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="person",
            name="phone_number",
            field=models.IntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(11),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                parent_link=True,
                to="person.person",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerininstitution",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institution",
            ),
        ),
        migrations.AlterField(
            model_name="volunteerininstitution",
            name="volunteer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="person.volunteer",
            ),
        ),
    ]
