# Generated by Django 4.1.1 on 2022-09-18 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("person", "0002_alter_healthprofessional_person_and_more")]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="person",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="person.person",
            ),
        )
    ]
