# Generated by Django 3.2 on 2022-09-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('person', '0004_patient_all_keys_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='care_center',
        ),
        migrations.AddField(
            model_name='patient',
            name='care_centers',
            field=models.ManyToManyField(to='institution.Institution'),
        ),
    ]
