# Generated by Django 3.2 on 2022-09-19 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20220918_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthprofessional',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person'),
        ),
    ]
