# Generated by Django 3.2 on 2022-10-15 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('drugbank', '0001_initial'),
        ('person', '0006_auto_20220919_0006'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='patient',
            name='all_keys_unique_together',
        ),
        migrations.AlterField(
            model_name='healthprofessional',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_centers',
            field=models.ManyToManyField(blank=True, to='institution.Institution'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='care_taker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='persons', to='person.person'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='health_insurance',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.healthinsurance'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugbank.drug'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.AlterField(
            model_name='volunteerininstitution',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
        migrations.AlterField(
            model_name='volunteerininstitution',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.volunteer'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, care_taker=django.db.models.expressions.F('person')), name='check_person_is_not_care_taker'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('name', 'dni'), name='name_and_dni_person_restiction'),
        ),
    ]
