# Generated by Django 3.2 on 2022-11-12 21:27

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20221112_2127'),
        ('drugbank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('prescription', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='dosage',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='drug',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 12, 21, 27, 25, 887112, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='drug',
            name='generic_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='drugbank',
            name='drugs',
            field=models.ManyToManyField(to='drugbank.Drug'),
        ),
        migrations.AddField(
            model_name='drugbank',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event'),
        ),
        migrations.AddField(
            model_name='drug',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drugbank.drugbatch'),
        ),
    ]
