# Generated by Django 3.2 on 2022-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
